version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server
    links:
      - server

  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    links:
      - db

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: foliotracker
      POSTGRES_USER: deathyvoid
      POSTGRES_PASSWORD: DEATHYVOID

volumes:
  pgdata: